"""add course and document tables

Revision ID: 21fe841fe1b6
Revises: 20b1a6ad1896
Create Date: 2026-01-29 21:46:11.427208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21fe841fe1b6'
down_revision: Union[str, Sequence[str], None] = '20b1a6ad1896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('semester', sa.String(length=50), nullable=False),
    sa.Column('class_name', sa.String(length=100), nullable=False),
    sa.Column('total_hours', sa.Integer(), nullable=False),
    sa.Column('practice_hours', sa.Integer(), nullable=False),
    sa.Column('course_type', sa.String(length=10), nullable=False),
    sa.Column('textbook_isbn', sa.String(length=50), nullable=False),
    sa.Column('textbook_name', sa.String(length=200), nullable=False),
    sa.Column('textbook_image', sa.String(length=500), nullable=False),
    sa.Column('textbook_publisher', sa.String(length=100), nullable=True),
    sa.Column('textbook_link', sa.String(length=500), nullable=True),
    sa.Column('course_catalog', sa.Text(), nullable=True),
    sa.Column('parent_course_id', sa.Integer(), nullable=True),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('share_key', sa.String(length=36), nullable=True),
    sa.Column('share_enabled', sa.Boolean(), nullable=False),
    sa.Column('share_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_index(op.f('ix_courses_parent_course_id'), 'courses', ['parent_course_id'], unique=False)
    op.create_index(op.f('ix_courses_share_key'), 'courses', ['share_key'], unique=True)
    op.create_index(op.f('ix_courses_user_id'), 'courses', ['user_id'], unique=False)
    op.create_table('course_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('lesson_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_documents_course_id'), 'course_documents', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_documents_id'), 'course_documents', ['id'], unique=False)
    # 添加唯一索引：确保 (course_id, doc_type, lesson_number) 的组合唯一
    # 这样可以保证单份文档（lesson_number 为 NULL）每个课程只有一份
    op.create_index(
        'ix_course_documents_unique_doc',
        'course_documents',
        ['course_id', 'doc_type', 'lesson_number'],
        unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_documents_id'), table_name='course_documents')
    op.drop_index(op.f('ix_course_documents_course_id'), table_name='course_documents')
    op.drop_table('course_documents')
    op.drop_index(op.f('ix_courses_user_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_share_key'), table_name='courses')
    op.drop_index(op.f('ix_courses_parent_course_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
